build site:
  image: node:10
  stage: build
  script:
    - npm install -g node-gyp
    - apt-get update
    - apt-get -y install python2.7 python-pip
    - apt-get -y install make
    - npm install --ignore-scripts --no-progress
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

## Deployment - Production
deploy:
  image: napp/docker-aws-cli
  stage: deploy
  when: manual
  script:
  - aws s3 cp --recursive ./dist/. s3://$AWS_BUCKET
  environment:
    name: production
    url: https://myapp.com
  only:
  - master

## Deployment - backend
deploy_backend:
  image: amaysim/serverless
  stage: deploy
  when: manual
  script:
  - serverless deploy
  only:
  - engine